# Makefile для фронтенда

install:
	npm ci || npm install

build:
	npm run build

start:
	npm run dev

dev:
	npm run dev

lint:
	npx eslint --ext js,jsx src

test:
	npm test

.PHONY: install build start dev lint test