install:
	cd frontend && npm install
	cd frontend && npm install react-redux @reduxjs/toolkit react-i18next i18next
	npm install

build:
	cd frontend && npm run build

start:
	cd frontend && npm run dev

lint:
	cd frontend && npx eslint --ext js,jsx src

.PHONY: install build start lint
