version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        cd code &&
        make install &&
        make build &&
        echo '=====================================' &&
        echo '✅✅✅ BUILD SUCCESSFUL! ✅✅✅' &&
        echo '=====================================' &&
        exit 0
      "