name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x] # <-- Вот здесь мы жестко указываем нужную версию

    steps:
      - uses: actions/checkout@v4

      - name: Использовать Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Установить зависимости
        run: npm install

      - name: Запустить тесты
        run: npm test